site_name: Rosa Trancoso Notebook's Share
site_description: My notebooks to share with the world
site_author: Rosa Trancoso
site_url: https://rosatrancoso.github.io/notebook-share

repo_url: https://github.com/rosatrancoso/notebook-share

copyright: "Copyright &copy; 2022 - 2023 Qiusheng Wu"

theme:
  palette:
    - scheme: default
      #   primary: blue
      #   accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - search.highlight
  custom_dir: "docs/overrides"
  font:
    text: Google Sans
    code: Regular

plugins:
  - search
  - mkdocstrings
  - git-revision-date
  - mkdocs-jupyter:
      include_source: True
      ignore_h1_titles: True
      execute: True
      allow_errors: True
      ignore: []
      execute_ignore: [
        # "chapter_01/*ipynb",
        # "chapter_02/*ipynb",
        # "chapter_03/folium_ipyleaflet_image_overlay.ipynb",
        # "chapter_03/plot_cartopy_img_tiles_examples.ipynb",
        # "chapter_03/plot_coastlines.ipynb",
        # "chapter_03/plot_dem_leaflet_image_overlay.ipynb",
        # "chapter_03/plot_lognorm_colorbar.ipynb",
        # "chapter_03/test_xarray_leaflet_simple.ipynb",
        ]

markdown_extensions:
  - attr_list
  - toc:
      permalink: true

extra:
  analytics:
    provider: google
    property: G-XXX

nav:
  - Home: index.md
  - Notebook:
      - template.ipynb
  - Leafmap:
      - leafmap/01_intro.ipynb
      - leafmap/02_basemaps.ipynb
      - leafmap/03_heatmap.ipynb
      - leafmap/04_wmslayer_colorbar.ipynb
      - leafmap/05_load_raster.ipynb
  - My Experiments:
      - experiments/folium_ipyleaflet_image_overlay.ipynb
      - experiments/plot_cartopy_img_tiles_examples.ipynb
      - experiments/plot_coastlines.ipynb
      - experiments/plot_dem_leaflet_image_overlay.ipynb
      - experiments/plot_lognorm_colorbar.ipynb
      - experiments/test_xarray_leaflet_simple.ipynb
  #- Blog: https://blog.gishub.org
  #- YouTube Channel: https://youtube.com/@giswqs
  - Report Issues: https://github.com/rosatrancoso/notebook-share/issues
