site_name: Rosa Trancoso Notebook's Share
site_description: My notebooks to share with the world
site_author: Rosa Trancoso
site_url: https://rosatrancoso.github.io/notebook-share

repo_url: https://github.com/rosatrancoso/notebook-share

copyright: "Copyright &copy; 2022 - 2023 Qiusheng Wu"

theme:
  palette:
    - scheme: default
      #   primary: blue
      #   accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - search.highlight
  custom_dir: "docs/overrides"
  font:
    text: Google Sans
    code: Regular

plugins:
  - search
  - mkdocstrings
  - git-revision-date
  - mkdocs-jupyter:
      include_source: True
      ignore_h1_titles: False
      execute: True
      allow_errors: True
      ignore: []
      execute_ignore: [  # cd docs; find . -name '*nb' | sort
        "geemap/*ipynb",
        "hydrology/*ipynb",
        "leafmap/*ipynb",
        "miscellaneous/*ipynb",
        "qva/*ipynb",

      # ./leafmap/02_basemaps.ipynb
      # ./leafmap/03_heatmap.ipynb
      # ./leafmap/04_wmslayer_colorbar.ipynb
      # ./leafmap/05_load_raster.ipynb
      # ./miscellaneous/plot_cartopy_img_tiles_examples.ipynb
      # ./miscellaneous/plot_cartopy_lambert_gridlines_dateline.ipynb
      # ./miscellaneous/plot_coastlines.ipynb
      # ./miscellaneous/plot_colorbar_discrete.ipynb
      # ./miscellaneous/plot_colorbar_common.ipynb
      # ./miscellaneous/plot_colorbar_lognorm.ipynb
      # ./miscellaneous/plot_image_overlay_folium_ipyleaflet.ipynb
      # ./miscellaneous/plot_image_overlay_ipyleaflet_terrain.ipynb
      # ./miscellaneous/test_xarray_leaflet_simple.ipynb
      # ./qva/plot_qva_det.ipynb
      # ./qva/plot_qva_prob.ipynb
      # ./hydrology/get_basin_reporoa.ipynb
            ]

markdown_extensions:
  - attr_list
  - toc:
      permalink: true

extra:
  analytics:
    provider: google
    property: G-XXX

nav:
  - Home: index.md
  - Hydrology:
      - hydrology/get_basin_reporoa.ipynb
  - Leafmap:
      - leafmap/02_basemaps.ipynb
      - leafmap/03_heatmap.ipynb
      - leafmap/04_wmslayer_colorbar.ipynb
      - leafmap/05_load_raster.ipynb
  - GEEmap:
      - geemap/landuse_app.ipynb 
  - Miscellaneous:
      - ./miscellaneous/plot_cartopy_img_tiles_examples.ipynb
      - ./miscellaneous/plot_cartopy_lambert_gridlines_dateline.ipynb
      - ./miscellaneous/plot_coastlines.ipynb
      - ./miscellaneous/plot_colorbar_discrete.ipynb
      - ./miscellaneous/plot_colorbar_common.ipynb
      # - ./miscellaneous/plot_colorbar_lognorm.ipynb
      - ./miscellaneous/plot_image_overlay_folium_ipyleaflet.ipynb
      # - ./miscellaneous/plot_image_overlay_ipyleaflet_terrain.ipynb
      # - ./miscellaneous/test_xarray_leaflet_simple.ipynb
  - QVA plots:
     - qva/plot_qva_det.ipynb
     - qva/plot_qva_prob.ipynb

  #- Blog: https://blog.gishub.org
  #- YouTube Channel: https://youtube.com/@giswqs
  - Report Issues: https://github.com/rosatrancoso/notebook-share/issues
